### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Chen-14** [xjw-nlp/SimMCS#3]
Hello author and thanks for the excellent work you have already provided. May I ask when the preprocessed dataset will be public?Thank you!

**Comment by xjw-nlp** [comment]
Thank you for your reminder, we have added the relevant datasets in the README.md."

**Comment by Chen-14** [comment]
Thank you for your help!

**Comment by Chen-14** [comment]
> Thank you for your reminder, we have added the relevant datasets in the README.md."

Maybe the permissions need to be adjusted. I don't have the download permissions.

**Comment by xjw-nlp** [comment]
Done!

----- 原始邮件 -----
发件人: "Chen-14" ***@***.***>
收件人: "xjw-nlp/SimMCS" ***@***.***>
抄送: "xjw-nlp" ***@***.***>, "Comment" ***@***.***>
发送时间: 星期四, 2024年 3 月 28日 下午 5:22:13
主题: Re: [xjw-nlp/SimMCS] Dataset (Issue #3)

> Thank you for your reminder, we have added the relevant datasets in the README.md."

Maybe the permissions need to be adjusted. I don't have the download permissions.
